[package]
name = "caustic-installer"
version = "0.1.0"
edition.workspace = true
publish.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
caustic-oci = { workspace = true }
directories = { workspace = true }
iced = { workspace = true, features = ["sipper", "tokio", "wayland", "wgpu"] }
sys-locale = { workspace = true }
tokio = { workspace = true, features = ["fs", "io-util", "macros", "process", "sync"] }
which = { workspace = true, features = ["real-sys"] }

[lints]
workspace = true
