[workspace]
resolver = "3"
members = [
    "crates/caustic-installer",
    "crates/caustic-oci",
    "crates/caustic-ota",
]

[workspace.package]
edition = "2024"
publish = false
repository = "https://github.com/stargrid-systems/caustic-os"
license = "AGPL-3.0-or-later"

[workspace.dependencies]
caustic-oci = { path = "crates/caustic-oci", default-features = false }

anyhow = { version = "1", default-features = false }
clap = { version = "4", default-features = false }
directories = { version = "6", default-features = false }
futures-util = { version = "0.3", default-features = false }
iced = { version = "0.14", default-features = false }
oci-client = { version = "0.17", default-features = false }
plist = { version = "1", default-features = false }
rfd = { version = "0.15", default-features = false }
rustix = { version = "1", default-features = false }
serde = { version = "1", default-features = false }
serde_json = { version = "1", default-features = false }
sha2 = { version = "0.11", default-features = false }
sys-locale = { version = "0.3", default-features = false }
tokio = { version = "1", default-features = false }
tracing = { version = "0.1", default-features = false }
tracing-subscriber = { version = "0.3", default-features = false }
which = { version = "8", default-features = false }

[workspace.lints.clippy]
cargo = { level = "warn", priority = -1 }
multiple_crate_versions = { level = "allow", priority = 0 }
nursery = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }

[profile.release]
strip = true
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
