[workspace]
resolver = "3"
members = [
    "crates/caustic-installer",
    "crates/caustic-oci",
    "crates/caustic-ota",
]

[workspace.package]
edition = "2024"
publish = false

[workspace.dependencies]
caustic-oci = { path = "crates/caustic-oci", default-features = false }

anyhow = { version = "1", default-features = false }
clap = { version = "4", default-features = false }
futures-util = { version = "0.3", default-features = false }
iced = { version = "0.14", default-features = false }
oci-client = { version = "0.17", default-features = false }
serde = { version = "1", default-features = false }
serde_json = { version = "1", default-features = false }
sha2 = { version = "0.11", default-features = false }
tokio = { version = "1", default-features = false }
tracing = { version = "0.1", default-features = false }
tracing-subscriber = { version = "0.3", default-features = false }
which = { version = "8", default-features = false }

[profile.release]
strip = true
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
