name: Test build

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  actions: write

jobs:
  build-dev-image:
    name: Build dev image
    runs-on: ubuntu-26.04-arm
    environment: dev
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
        with:
          persist-credentials: false

      - name: Enable unprivileged user namespaces
        run: |
          sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0 || true
          cat /proc/sys/kernel/apparmor_restrict_unprivileged_userns || true
          cat /proc/sys/user/max_user_namespaces || true

      - name: Install Determinate Nix
        uses: DeterminateSystems/determinate-nix-action@2a0be2498974c2b6327e19780488744384637d88  # v3.21.7

      - name: FlakeHub Cache
        uses: DeterminateSystems/flakehub-cache-action@3be0931021788e3bb4df65f59a555039c2fa2d46  # v3.21.7

      - name: Build dev update package
        run: |
          nix build \
            .#nixosConfigurations.devImage.config.system.build.updatePackage \
            --out-link update \
            --print-build-logs
